# Generated by Django 5.2.1 on 2025-07-06 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='privateconversation',
            index=models.Index(fields=['participant2', 'participant1'], name='chat_privat_partici_0842b0_idx'),
        ),
    ]
