# Generated by Django 5.2.1 on 2025-07-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privateconversation_chat_privat_partici_0842b0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='private_messages/images/'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
