# Generated by Django 5.2.1 on 2025-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='location',
            field=models.CharField(blank=True, help_text='Città o luogo associato alla petizione', max_length=255),
        ),
    ]
