# Generated by Django 5.2.1 on 2025-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approvata'), ('REJECT', 'Rifiutata'), ('DELETE', 'Cancellata'), ('FLAG', 'Segnalata'), ('ARCHIVE', 'Archiviata')], max_length=20),
        ),
    ]
