# Generated by Django 5.2.1 on 2025-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0005_alter_moderationaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
