# Generated by Django 5.2.1 on 2025-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_petitionview_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignature',
            name='first_name',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingsignature',
            name='last_name',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
