# Generated by Django 5.2.1 on 2025-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_pendingsignature_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('petition_comment', 'Commento Petizione'), ('chat_message', 'Messaggio Chat'), ('petition_vote', 'Voto Petizione'), ('petition_signature', 'Firma Petizione'), ('petition_update', 'Aggiornamento Petizione'), ('report', 'Segnalazione')], default='petition_comment', max_length=30),
            preserve_default=False,
        ),
    ]
